-- Jalankan sekali di Supabase SQL Editor. Akun pengurus harus ada di Supabase Authentication.
create table if not exists public.catalog_products (
 id bigint generated by default as identity primary key,
 name text not null check (length(trim(name)) > 0),
 price numeric(12,0) not null check (price >= 0),
 image_url text not null default '',
 category text not null check (length(trim(category)) > 0),
 description text not null default '',
 tambahan_biaya boolean not null default false,
 promo_qty integer check (promo_qty is null or promo_qty > 1),
 promo_price numeric(12,0) check (promo_price is null or promo_price >= 0),
 is_active boolean not null default true,
 sort_order integer not null default 0,
 created_at timestamptz not null default now(),
 constraint promo_pair check ((promo_qty is null) = (promo_price is null))
);
-- Izinkan pembacaan katalog kepada pengunjung, tetapi semua perubahan hanya untuk akun Auth pengurus.
alter table public.catalog_products enable row level security;
create or replace function public.is_fikri_admin() returns boolean
language sql security definer set search_path = public, pg_temp as $$
 select exists(select 1 from public.admin_users where lower(email) = lower((select auth.jwt() ->> 'email')));
$$;
revoke all on function public.is_fikri_admin() from public;
grant execute on function public.is_fikri_admin() to authenticated;
drop policy if exists "Katalog publik" on public.catalog_products;
create policy "Katalog publik" on public.catalog_products for select to anon, authenticated using (true);
drop policy if exists "Pengurus tambah katalog" on public.catalog_products;
create policy "Pengurus tambah katalog" on public.catalog_products for insert to authenticated with check (public.is_fikri_admin());
drop policy if exists "Pengurus ubah katalog" on public.catalog_products;
create policy "Pengurus ubah katalog" on public.catalog_products for update to authenticated using (public.is_fikri_admin()) with check (public.is_fikri_admin());
drop policy if exists "Pengurus hapus katalog" on public.catalog_products;
create policy "Pengurus hapus katalog" on public.catalog_products for delete to authenticated using (public.is_fikri_admin());
grant select on public.catalog_products to anon;
grant select, insert, update, delete on public.catalog_products to authenticated;
grant usage, select on sequence public.catalog_products_id_seq to authenticated;
-- Impor awal idempotent: tidak menggandakan produk jika dijalankan kembali.
insert into public.catalog_products (name, price, image_url, category, description, tambahan_biaya, promo_qty, promo_price, sort_order)
select seed.name, seed.price, seed.image_url, seed.category, seed.description, seed.tambahan_biaya, seed.promo_qty, seed.promo_price, seed.sort_order
from (values
('Gas Elpiji 3kg', 22000, 'images/gas-3kg.jpg', 'GAS ELPIJI', '
  🔥 Gas Elpiji 3 Kg resmi Pertamina asli - aman & berkualitas.
  Jaminan Kualitas:
  ✔ Segel resmi Pertamina utuh  
  ✔ Berat & tekanan gas sesuai standar  
  ✔ Tidak diisi ulang ilegal  
  ✔ Tabung lolos pengecekan keamanan
  ', true, null, null, 1),
('Gas Elpiji 12kg', 260000, 'images/gas-12kg.jpg', 'GAS ELPIJI', '
  🔥 Gas Elpiji 12 Kg resmi pertamina asli, segel resmi, dan tanpa pengurangan isi.
  Jaminan Kualitas:
  ✔ Segel asli Pertamina masih utuh
  ✔ Bukan isi ulang ilegal
  ✔ Berat sesuai standar 12 Kg
  ✔ Tekanan gas stabil dan optimal
  ✔ Tabung sudah lulus uji keamanan
  ', true, null, null, 2),
('Aqua Galon', 23000, 'images/aqua-galon.jpg', 'MINUMAN', '
  💧 AQUA Galon Asli – Segar, Bersih, dan Terpercaya!
  Di luar sana banyak beredar galon yang diisi ulang manual tanpa standar kebersihan. 
  Tapi di sini, Anda mendapatkan AQUA yang langsung dari pabrik, dengan kualitas air pegunungan yang terjaga.
  Jaminan Kualitas:
  ✔ Segel resmi AQUA masih utuh
  ✔ Bukan galon isi ulang atau oplosan
  ✔ Rasa tetap segar, murni, dan standar pabrik
  ✔ Galon higienis dan terawat
  ', true, null, null, 3),
('Aqua 600ml', 52000, 'images/aqua-600ml.jpg', 'MINUMAN', '
  💧 AQUA 600 ml Original – Segar, Murni, dan Terpercaya!
  AQUA 600 ml yang kami jual 100% asli pabrik, dengan segel utuh, label resmi, dan bukan air isi ulang atau repacking.
  Jadi Anda tidak perlu khawatir soal kualitas atau kebersihan.
  Jaminan Keaslian & Kebersihan:
  ✔ Botol original AQUA, bukan tiruan
  ✔ Segel tutup rapat dan tidak pernah dibuka
  ✔ Air murni dari sumber pegunungan
  ✔ Standar pabrik terjaga — aman dan higienis
  ✔ 1 Karton isi 24 Botol
  ', true, null, null, 4),
('Aqua 330ml', 42000, 'images/aqua-330ml.jpg', 'MINUMAN', '
  💧 AQUA 330 ml Original – Segar, Murni, dan Terpercaya!
  AQUA 330 ml yang kami jual 100% asli pabrik, dengan segel utuh, label resmi, dan bukan air isi ulang atau repacking.
  Jadi Anda tidak perlu khawatir soal kualitas atau kebersihan.
  Jaminan Keaslian & Kebersihan:
  ✔ Botol original AQUA, bukan tiruan
  ✔ Segel tutup rapat dan tidak pernah dibuka
  ✔ Air murni dari sumber pegunungan
  ✔ Standar pabrik terjaga — aman dan higienis
  ✔ 1 Karton isi 24 Botol
  ', true, null, null, 5),
('Aqua Cube', 40000, 'images/aqua-cube.jpg', 'MINUMAN', '
  💧 AQUA Cube Original – Praktis, Segar, dan Higienis!
  Produk ini 100% original dari AQUA, dengan segel utuh, kemasan Food Grade, dan bukan repacking atau isi ulang
  Jaminan Keaslian & Kualitas:
  ✔ Segel pabrik masih utuh
  ✔ Bukan isi ulang atau kemasan ulang
  ✔ Air murni dari sumber pegunungan AQUA
  ✔ Dijamin aman, higienis, dan fresh
  ✔ 1 Karton isi 24 Botol
    ', true, null, null, 6),
('Aqua Gelas', 35000, 'images/aqua-gelas.jpg', 'MINUMAN', '
    💧 AQUA Gelas Original – Segar, Higienis, dan Terpercaya!
    AQUA Gelas adalah pilihan terbaik untuk kebutuhan minuman praktis di rumah, kantor, sekolah, acara, hingga usaha kuliner.
    Produk yang kami jual 100% asli pabrik, dengan segel plastik utuh dan bukan isi ulang atau kemasan ulang.
    Jaminan Keaslian Produk:
    ✔ Segel plastik pabrik masih utuh
    ✔ Tidak pernah dibuka atau dipindah isi
    ✔ Logo dan label asli AQUA
    ✔ Diproduksi dengan standar kualitas nasional & internasional
    ✔ 1 Karton isi 48 Cup/Gelas
    ', true, null, null, 7),
('Aqua 1,5 Liter', 55000, 'images/aqua-1,5ltr.jpg', 'MINUMAN', '
    💧 AQUA Gelas Original – Segar, Higienis, dan Terpercaya!
    AQUA Gelas adalah pilihan terbaik untuk kebutuhan minuman praktis di rumah, kantor, sekolah, acara, hingga usaha kuliner.
    Produk yang kami jual 100% asli pabrik, dengan segel plastik utuh dan bukan isi ulang atau kemasan ulang.
    Jaminan Keaslian Produk:
    ✔ Segel plastik pabrik masih utuh
    ✔ Tidak pernah dibuka atau dipindah isi
    ✔ Logo dan label asli AQUA
    ✔ Diproduksi dengan standar kualitas nasional & internasional
    ✔ 1 Karton isi 12 Botol
    ', true, null, null, 8),
('leMineral Galon', 22000, 'images/lemineral-galon.jpg', 'MINUMAN', '
    💧 Le Minerale – Air Mineral dari Mayora Group
    Air mineral Le Minerale berasal dari sumber mata air pegunungan yang kaya mineral alami.
    Untuk menjaga kualitasnya, Le Minerale menggunakan kemasan segel khusus yang melindungi kesegaran dan kandungan mineral tetap utuh sampai ke tangan konsumen.
    Kenapa Le Minerale?
    ✔ Sumber air pegunungan asli
    ✔ Mengandung mineral alami penting
    ✔ Rasa lebih segar dan tidak hambar
    ✔ Dikemas menggunakan teknologi modern
    ✔ Diproduksi oleh perusahaan besar dan terpercaya
    ', true, null, null, 9),
('leMineral 330ml', 42000, 'images/lemineral-330ml.jpg', 'MINUMAN', '
    💧 Le Minerale 330 ml Original – Segar, Praktis, dan Kaya Mineral Alami!
    Setiap botol Le Minerale 330 ml yang kami jual 100% original, Dibuat oleh PT Tirta Fresindo Jaya (Mayora Group).
    Segel pabrik masih utuh, dan bukan isi ulang atau repacking.
    sehingga kualitas rasa dan mineralnya tetap terjaga.
    aminan Keaslian Produk:
    ✔ Botol original Le Minerale, bukan tiruan
    ✔ Tutup segel pabrik masih rapat
    ✔ Tidak pernah dibuka atau diisi ulang
    ✔ Diproduksi dengan standar higienis modern
    ✔ 1 Karton isi 24 Botol
    ', true, null, null, 10),
('leMineral 600ml', 52000, 'images/lemineral-600ml.jpg', 'MINUMAN', '
    💧 Le Minerale 600 ml – Segar, Murni, dan Kaya Mineral Alami!
    Dibuat oleh PT Tirta Fresindo Jaya (Mayora Group), Le Minerale berasal dari sumber mata air pegunungan yang mengandung mineral alami penting bagi tubuh.
    Produk ini 100% asli, segel botol masih utuh, dan bukan isi ulang, sehingga rasa, kebersihan, dan kandungan mineralnya tetap terjaga.
    Jaminan Keaslian & Kebersihan:
    ✔ Segel tutup rapat dan original
    ✔ Botol bukan repacking atau isi ulang
    ✔ Diproduksi dengan standar higienis modern
    ✔ Kualitas terkontrol langsung dari pabrik
    ✔ 1 Karton isi 24 Botol
    ', true, null, null, 11),
('Beras 14 Petruk', 15500, 'images/beras-14.jpg', 'BERAS', '
    🌾 Beras Petruk Premium — Pulen, Wangi, dan Berkualitas Tinggi!
    Beras Petruk dikenal sebagai salah satu beras terbaik pilihan keluarga Indonesia.
    Beras Petruk yang kami jual 100% murni, bukan oplosan, dan bukan dicampur beras lain.
    Jaminan Kualitas Produk:
    ✔ Bersih dan sudah diseleksi
    ✔ Bukan beras oplosan atau campuran
    ✔ Tidak mengandung bahan pengawet atau pemutih
    ✔ Hasil nasi pulen, lembut, dan wangi
    ', true, null, null, 12),
('Beras 13 Cap Kelapa 3', 14500, 'images/beras-13.jpg', 'BERAS', '
    🌾 Beras Cap 3 Kelapa Solo – Pulen, Bersih, dan Rasa Lebih Nikmat!
    Beras Cap 3 Kelapa Solo dikenal sebagai beras pilihan keluarga yang memiliki kualitas premium dengan rasa yang khas.
    Produk yang kami jual 100% asli, fresh dari karung asli pabrik, dan bukan oplosan atau campuran jenis beras lain.
    Jaminan Kualitas & Keaslian:
    ✔ Beras murni Cap 3 Kelapa Solo
    ✔ Bukan beras oplosan atau dicampur
    ✔ Bersih, alami tanpa pengawet & pemutih
    ✔ Hasil nasi pulen, fluffy, dan konsisten
    ', true, null, null, 13),
('Beras 12 Batik Solo', 13500, 'images/beras-12.jpg', 'BERAS', '
    🌾 Beras Batik Solo – Pulen, Bersih, dan Kualitas Premium Untuk Keluarga!
    Beras Batik Solo adalah pilihan tepat bagi Anda yang menginginkan nasi dengan kualitas terbaik.
    Produk ini 100% asli, bukan oplosan, dan diproses dengan standar kebersihan tinggi, sehingga kualitas beras tetap terjaga mulai dari petani.
    Jaminan Kualitas & Keaslian:
    ✔ Beras murni Batik Solo, bukan campuran
    ✔ Bersih, tanpa batu & kotoran
    ✔ Tidak memakai pemutih, pewangi, atau bahan kimia
    ✔ Dipilih dari butiran beras premium
    ', true, null, null, 14),
('Tepung Terigu (Lencana Merah)', 10000, 'images/tepung-terigu.jpg', 'BUMBU DAPUR', '
    🌾 Tepung Terigu Lencana Merah – Hasil Adonan Lebih Lembut & Mengembang Sempurna!
    Tepung Terigu Lencana Merah dari Bogasari adalah pilihan tepat untuk kebutuhan dapur dan usaha Anda.
    Terbuat dari gandum pilihan berkualitas tinggi, tepung ini menghasilkan adonan yang lembut, elastis, dan mudah diolah untuk berbagai jenis makanan.
    Jaminan Kualitas & Keaslian:
    ✔ Produk asli Bogasari
    ✔ Terbuat dari gandum pilihan berkualitas
    ✔ Tekstur halus & bersih
    ✔ Aman & higienis, diproses dengan standar pabrik modern
    ', true, null, null, 15),
('Tepung Terigu (Segitiga Biru)', 13000, 'images/segitiga-biru.jpg', 'BUMBU DAPUR', '
    🌾 Tepung Terigu Segitiga Biru Bogasari 1 kg – Serbaguna & Berkualitas!
    Tepung serbaguna yang cocok untuk berbagai olahan masakan dan kue.
    Terbuat dari gandum pilihan dengan kualitas terjaga, menghasilkan adonan yang halus, lembut, dan mudah diolah.
    Jaminan Kualitas & Keaslian:
    ✔ Produk asli Bogasari
    ✔ Tekstur halus & bersih
    ✔ Hasil adonan lembut & tidak mudah keras
    ✔ Dikemas rapi & higienis 1 kg
    ', true, null, null, 16),
('Gula Pasir (Kristal) GMP', 20000, 'images/gula-pasir.jpg', 'BUMBU DAPUR', '
    🍬 Gula Pasir Kristal GMP – Manis Alami, Bersih, dan Berkualitas!
    Gula Pasir Kristal GMP merupakan pilihan tepat untuk kebutuhan rumah tangga maupun usaha.
    Dihasilkan dari tebu pilihan dan diproses dengan teknologi modern, menghasilkan kristal gula yang putih, bersih, dan manis alami.
    Jaminan Kualitas & Keaslian:
    ✔ Gula pasir kristal GMP asli
    ✔ Manis alami, mudah larut
    ✔ Tanpa campuran & aman dikonsumsi
    ✔ Diproses sesuai standar mutu pangan
    ', true, null, null, 17),
('Telur 1kg', 30000, 'images/telur.jpg', 'TELUR', '
    🥚 Telur Ayam Segar – Besar, Bersih, & Kualitas Terjamin!
    Telur ayam adalah bahan pangan serbaguna yang cocok untuk kebutuhan dapur harian, usaha kuliner, bakery, warung makan, hingga stok rumah tangga.
    Telur yang kami jual 100% fresh, kami hanya menyediakan telur pilihan dari peternak terpercaya, sehingga kualitas, ukuran, dan kesegarannya lebih terjamin.
    Jaminan Mutu & Keamanan:
    ✔ Telur selalu fresh, bukan stok lama
    ✔ Kualitas terjaga dari peternak sampai ke pelanggan
    ', true, null, null, 18),
('Minyak Kita 1ltr', 22000, 'images/minyak-1ltr.jpg', 'MINYAK', '
    🛢️ Minyak Kita Original – Minyak Goreng Higienis & Lebih Terjamin!
    Minyak Kita merupakan minyak goreng pilihan masyarakat yang diproduksi dengan standar pemerintah dan proses yang higienis.
    Dibuat dari minyak sawit berkualitas dan telah melalui proses penyaringan sehingga menghasilkan minyak yang jernih, tidak mudah hitam, dan hemat digunakan.
    Produk yang kami jual 100% resmi dan original.
    Jaminan Keaslian & Kualitas:
    ✔ Produk resmi Minyak Kita
    ✔ Aman, bersih, dan siap pakai
    ✔ 1 Karton ini 12 pcs = 12 Liter
    ', true, 12, 230000, 19),
('Minyak Kita 2ltr', 44000, 'images/minyak-1ltr.jpg', 'MINYAK', '
    🛢️ Minyak Kita Original – Minyak Goreng Higienis & Lebih Terjamin!
    Minyak Kita merupakan minyak goreng pilihan masyarakat yang diproduksi dengan standar pemerintah dan proses yang higienis.
    Dibuat dari minyak sawit berkualitas dan telah melalui proses penyaringan sehingga menghasilkan minyak yang jernih, tidak mudah hitam, dan hemat digunakan.
    Produk yang kami jual 100% resmi dan original.
    Jaminan Keaslian & Kualitas:
    ✔ Produk resmi Minyak Kita
    ✔ Aman, bersih, dan siap pakai
    ✔ 1 Karton ini 6 pcs = 12 Liter
    ', true, 6, 230000, 20),
('Minyak Goreng Rizki', 18000, 'images/minyak-rizki.jpg', 'MINYAK', '
   🛢️ Minyak Goreng Rizki 800 ml – Jernih, Hemat, dan Berkualitas!
   Minyak Goreng Rizki 800 ml adalah pilihan tepat untuk kebutuhan memasak sehari-hari.
   Dihasilkan dari bahan baku pilihan dan diproses dengan standar mutu yang baik, membantu menghasilkan masakan yang lebih renyah dan lezat.
    Jaminan Keaslian & Kualitas:
    ✔ Minyak goreng jernih & bersih
    ✔ Tidak berbau tengik
    ✔ Stabil saat digunakan untuk menggoreng
    ✔ Dikemas higienis & praktis 800 ml
    ✔ Aman digunakan untuk kebutuhan dapur sehari-hari
    ', true, null, null, 21),
('Good Day Mocacinno - Isi 10', 20000, 'images/goo-daymocacinno.jpg', 'MINUMAN SASET', '
    ☕ Good Day Mocacinno – Kopi Nikmat dengan Sensasi Cokelat yang Menggoda!
    Good Day Mocacinno adalah pilihan tepat bagi kamu yang suka kopi dengan perpaduan rasa kopi dan cokelat yang creamy dan nikmat.
    Praktis disajikan panas maupun dingin, Good Day Mocacinno siap menjadi teman ngopi favorit setiap hari.
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel rapi
    ✔ Aman dan praktis untuk dikonsumsi
    ', true, null, null, 22),
('Good Day Cappucinno - Isi 10', 25000, 'images/cappuccino.jpg', 'MINUMAN SASET', '
    ☕ Good Day Cappuccino – Kopi Nikmat dengan Sensasi Cokelat yang Menggoda!
    Good Day Cappuccino adalah pilihan tepat bagi kamu yang suka kopi dengan perpaduan rasa kopi dan cokelat yang creamy dan nikmat.
    Praktis disajikan panas maupun dingin, Good Day Mocacinno siap menjadi teman ngopi favorit setiap hari.
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel rapi
    ✔ Aman dan praktis untuk dikonsumsi
    ', true, null, null, 23),
('Gula Merah - 1Kg', 20000, 'images/gula-merah.jpg', 'BUMBU DAPUR', '
    🍬 Gula Merah – Manis Alami!
    Gula merah menjadi pilihan tepat untuk memberikan rasa manis khas dan aroma yang lebih harum pada berbagai hidangan.
    Cocok digunakan untuk membuat kue, jajanan tradisional, minuman, saus, hingga berbagai masakan favorit keluarga.
    Jaminan Produk:
    ✔ Produk berkualitas
    ✔ Dikemas dengan rapi
    ✔ Cocok untuk berbagai kebutuhan masak
    ✔ Aroma dan rasa khas gula merah
    ', true, null, null, 24),
('Kecap Nasional 700 Gram', 17500, 'images/kecap-nasional.jpg', 'BUMBU DAPUR', '
    🥢 Kecap Nasional – Manis di Setiap Masakan!
    Kecap Nasional siap melengkapi berbagai hidangan favorit keluarga dengan perpaduan rasa manis dan gurih yang nikmat.
    Cocok digunakan untuk nasi goreng, mie goreng, sate, ayam, tahu, tempe, tumisan, hingga berbagai masakan lainnya.
    Jaminan Keaslian:
    ✔ Siap digunakan untuk berbagai masakan
    ', true, null, null, 25),
('Indocafe Coffeemix - Isi 10', 20000, 'images/indocafe.jpg', 'MINUMAN SASET', '
    ☕ Indocafe Coffeemix – Kopi 3 in 1!
    Indocafe Coffeemix adalah pilihan praktis untuk menikmati kopi dengan perpaduan kopi, gula, dan krimer dalam satu sajian.
    Tinggal seduh dengan air panas, kopi siap dinikmati kapan saja.
    Jaminan Keaslian:
    ✔ Praktis diseduh kapan saja
    ', true, null, null, 26),
('Kapal Api Tanpa Gula - Isi 11', 16500, 'images/kapal-api-tanpagula.jpg', 'MINUMAN SASET', '
    ☕ Kapal Api Tanpa Gula – Kopi Mantap untuk Pecinta Kopi Tanpa Gula!**
    Kapal Api Tanpa Gula cocok untuk kamu yang ingin menikmati kopi dengan rasa khas tanpa tambahan gula. 
    Aromanya yang kuat dan cita rasa kopinya pas untuk menemani aktivitas sehari-hari.
    🎁 PROMO SPESIAL: BELI 10 GRATIS 1!
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel rapi
    ✔ Tanggal kedaluwarsa jelas
    ✔ Cocok untuk stok di rumah maupun usaha
    ', true, null, null, 27),
('Kapal Api Mix Gula - Isi 10', 20000, 'images/kopihitam.jpg', 'MINUMAN SASET', '
    ☕ Kapal Api Mix Gula – Kopi Nikmat, Praktis, dan Pas untuk Teman Beraktivitas!
    Kapal Api Mix Gula menghadirkan perpaduan kopi dan gula dalam satu kemasan praktis.
    Tinggal seduh dengan air panas, aduk, dan kopi siap dinikmati. Pas untuk menemani pagi, bekerja, belajar, maupun waktu santai.
    Jaminan Keaslian:
    ✔ Kemasan tersegel
    ✔ Tanggal kedaluwarsa jelas
    ✔ Praktis dan mudah disajikan
    ', true, null, null, 28),
('LADAKU Isi 12', 12000, 'images/ladaku.jpg', 'BUMBU DAPUR', '
    🌶️ Ladaku – Lada Berkualitas untuk Masakan Lebih Harum dan Sedap!
    Ladaku siap membantu memberikan aroma dan cita rasa lada yang khas pada berbagai masakan.
    Cocok digunakan untuk sup, tumisan, ayam, daging, seafood, mie, nasi goreng, dan berbagai menu lainnya.
    Praktis digunakan sehari-hari dan cocok menjadi salah satu bumbu wajib di dapur.
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel rapi
    ✔ Tanggal kedaluwarsa jelas
    ✔ Praktis digunakan untuk berbagai masakan
    ', true, null, null, 29),
('Luwak White Koffie Isi 10', 20000, 'images/luwak-whitekoffie.jpg', 'MINUMAN SASET', '
    ☕ Luwak White Koffie – Kopi Putih dengan Rasa Lembut dan Nikmat!
    Luwak White Koffie hadir untuk kamu yang menyukai kopi dengan cita rasa lembut dan aroma yang khas.
    Nikmati sensasi kopi putih yang praktis disajikan kapan saja.
    Cukup seduh dengan air panas dan aduk hingga rata. Cocok menemani sarapan, bekerja, belajar, maupun waktu santai bersama keluarga.
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel
    ✔ Tanggal kedaluwarsa jelas
    ✔ Praktis disajikan kapan saja
    ', true, null, null, 30),
('Mama Lemon', 10000, 'images/mamalimon.jpg', 'SABUN CUCI PIRING', '
    🍋 Mama Lemon Sunlight – Bersih Maksimal, Wangi Segar, dan Ampuh Angkat Lemak!
    Mama Lemon Sunlight adalah sabun cuci piring yang praktis digunakan untuk membantu membersihkan berbagai peralatan makan dan masak dari sisa makanan serta lemak.
    Pilihan praktis untuk menjaga peralatan makan dan dapur tetap bersih setelah digunakan.
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel rapi
    ✔ Kemasan dan isi sesuai produk
    ✔ Cocok untuk kebutuhan rumah tangga maupun usaha kuliner
    ', true, null, null, 31),
('Masako Sapi Isi 12', 6000, 'images/masako-sapi.jpg', 'BUMBU DAPUR', '
    🥩 Masako Rasa Sapi – Bumbu Kaldu untuk Masakan Lebih Gurih dan Lezat!
    Masako Rasa Sapi siap membantu menambah cita rasa gurih dan aroma kaldu pada berbagai masakan.
    Cocok digunakan untuk sup, tumisan, nasi goreng, mie, sayur, dan berbagai menu keluarga lainnya.
    Praktis digunakan sehari-hari untuk membantu membuat masakan semakin nikmat.
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel
    ✔ Tanggal kedaluwarsa jelas
    ✔ Praktis untuk berbagai jenis masakan
    ', true, null, null, 32),
('Nutrisari Jeruk Peras Isi 10', 20000, 'images/nutrisari.jpg', 'MINUMAN SASET', '
    🍊 Nutrisari Jeruk Peras – Rasa Jeruk Segar yang Cocok untuk Kapan Saja!
    Nutrisari Jeruk Peras menghadirkan sensasi rasa jeruk yang segar dan nikmat dalam sajian praktis.
    Cocok dinikmati saat cuaca panas, menemani waktu santai, maupun menjadi minuman favorit keluarga.
    Tinggal larutkan dengan air, sajian minuman jeruk siap dinikmati.
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel rapi
    ✔ Tanggal kedaluwarsa jelas
    ✔ Praktis disajikan kapan saja
    ', true, null, null, 33),
('Sasa 250 Gram', 15000, 'images/sasa250g.jpg', 'BUMBU DAPUR', '
    🧂 Sasa 250 g – Penyedap Rasa untuk Masakan Lebih Gurih dan Nikmat!
    Sasa hadir sebagai penyedap rasa yang praktis digunakan untuk berbagai masakan sehari-hari.
    Cocok ditambahkan pada sup, tumisan, nasi goreng, mie, sayuran, dan berbagai hidangan favorit keluarga.
    Dengan kemasan 250 g, cocok untuk kebutuhan dapur maupun sebagai stok penyedap di rumah.
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel rapi
    ✔ Berat sesuai kemasan
    ✔ Tanggal kedaluwarsa jelas
    ', true, null, null, 34),
('Tea Jus Gula Batu Isi 10', 5000, 'images/teajus.jpg', 'MINUMAN SASET', '
    🧊 Tea Jus Gula Batu – Minuman Teh Manis yang Segar dan Praktis!
    Tea Jus Gula Batu merupakan minuman serbuk rasa teh dengan sensasi manis yang pas dan menyegarkan.
    Praktis disajikan kapan saja, terutama saat cuaca panas atau sebagai teman bersantai.
    Cukup larutkan dengan air dan tambahkan es batu untuk mendapatkan minuman yang lebih segar dan nikmat.
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel
    ✔ Tanggal kedaluwarsa jelas
    ✔ Praktis disajikan kapan saja
    ', true, null, null, 35),
('Garam Segitifa Emas 250 Gram', 4000, 'images/garam-segitigaemas.jpg', 'BUMBU DAPUR', '
    🧂 Garam Segitiga Emas – Pelengkap Wajib untuk Masakan Sehari-hari!
    Garam Segitiga Emas cocok digunakan sebagai pelengkap berbagai masakan sehari-hari.
    Membantu memberikan rasa asin yang pas pada sayur, tumisan, sup, gorengan, dan berbagai hidangan favorit keluarga.
    Cocok untuk kebutuhan dapur rumah tangga, warung makan, maupun usaha kuliner.
    Jaminan Keaslian:
    ✔ Produk original & resmi
    ✔ Kemasan tersegel rapi
    ✔ Berat sesuai kemasan
    ✔ Cocok untuk kebutuhan dapur sehari-hari
    ', true, null, null, 36),
('Teh Pucuk Harum 350ML', 65000, 'images/teh-pucuk.jpg', 'MINUMAN', '
    🍃 Teh Pucuk Harum 350 ml – Segarnya Teh dari Pucuk Daun Pilihan!
    Teh Pucuk Harum dibuat dari pucuk daun teh terpilih yang menghasilkan rasa teh alami, harum, dan menyegarkan.
    Diproses dengan teknologi modern untuk menjaga aroma dan kesegaran teh dalam setiap botol.
    Jaminan Keaslian & Kebersihan:
    ✔ Terbuat dari pucuk daun teh pilihan
    ✔ Rasa teh alami & tidak pahit
    ✔ Aroma harum khas teh
    ✔ Kemasan praktis 350 ml
    ✔ Higienis & siap minum
    ', true, null, null, 37),
('Teh Sosro Celup', 8000, 'images/teh-sosro.jpg', 'MINUMAN SASET', '
    🍵 Teh Celup Sosro Isi 30 – Teh Asli Indonesia, Harum & Berkualitas!
    Teh Celup Sosro dibuat dari daun teh pilihan terbaik yang dipetik dan diolah dengan standar mutu tinggi, menghasilkan rasa teh yang khas, harum, dan menyegarkan.
    🔒 Jaminan Kualitas & Keaslian:
    ✔ Produk asli Sosro
    ✔ Daun teh pilihan berkualitas
    ✔ Aroma harum & rasa teh khas
    ✔ Praktis dengan kemasan isi 30 celup
    ✔ Higienis & aman dikonsumsi
    ', true, null, null, 38),
('S-TEE', 60000, 'images/s-tee.jpg', 'MINUMAN', '
    🍹S-TEE Teh Manis – Segar, Nikmat, dan Pas di Kantong!
    S-TEE adalah minuman teh siap minum yang terkenal dengan rasa manisnya yang pas dan kesegarannya yang bikin nagih. 
    Dibuat dari ekstrak teh berkualitas dan diproses dengan standar higienis modern, S-TEE menjadi pilihan favorit untuk menemani aktivitas harian.
    Produk yang kami jual 100% original, segel pabrik masih rapat.
    Jaminan Keaslian:
    ✔ Segel utuh & resmi pabrik
    ✔ Bukan oplosan / repack
    ✔ Tanggal kedaluwarsa jelas & aman dikonsumsi
    ✔ Dikemas langsung dengan standar food grade
    ', true, null, null, 39),
('Teh Botol Sosro', 60000, 'images/teh-botol.jpg', 'MINUMAN', '
    "Ahlinya Teh Sejak 1940"
    Teh Botol Sosro adalah minuman teh siap minum yang dibuat dari daun teh berkualitas tinggi dan gula asli tanpa pemanis buatan. 
    Dengan cita rasa khas teh Jawa yang segar dan harum, Teh Botol Sosro menjadi pilihan favorit banyak orang sebagai minuman pendamping makan atau pelepas dahaga kapan saja.
    Teh Botol Sosro tetap menjadi minuman teh nomor satu yang menjaga rasa dan kualitasnya sejak dulu.
    ', true, null, null, 40),
('Tissue Paseo', 12000, 'images/paseo.jpg', 'TISSUE', '
    "Lembut, Higienis, dan Aman untuk Semua Jenis Kulit"
    Paseo merupakan tisu premium yang dibuat dari 100% serat alami, tanpa bahan pemutih berbahaya.
    Teksturnya lembut, tidak mudah sobek, dan memiliki daya serap tinggi sehingga nyaman digunakan untuk keperluan wajah, tangan, dan area sensitif lainya.
    Passeo 500 Extra 40 sheet adalah pilihan tepat untuk Anda yang menginginkan tisu berkualitas premium dengan isi lebih banyak dan daya tahan lebih kuat.
    Dengan 3 lapisan (3 Ply), tisu ini terasa lebih tebal namun tetap lembut di kulit.
    ', true, 3, 35000, 41),
('Tissue Jolly', 9000, 'images/jolly.jpg', 'TISSUE', '
    "Lembut, Hemat, dan Serbaguna untuk Kebutuhan Harian"
    Tissue Jolly 250 Sheet hadir sebagai pilihan tisu yang praktis, lembut, dan ekonomis untuk penggunaan sehari-hari.
    Dibuat dari bahan yang higienis dan memiliki daya serap baik.
    Dengan jumlah 250 lembar, tisu ini menawarkan penggunaan lebih lama dan tetap terjangkau. 
    Teksturnya tidak mudah robek, halus di kulit, dan aman digunakan oleh seluruh anggota keluarga.
    ', true, 3, 25000, 42),
('Tissue Nice', 7000, 'images/nice.jpg', 'TISSUE', '
    "Lembut, Kuat, dan Hemat untuk Penggunaan Sehari-hari"
    Tissue Nice 360 helai dengan ketebalan 2 ply hadir dengan kualitas lembut dan daya serap yang baik.
    Dengan teknologi higienis dan bahan pilihan berkualitas, Nice aman digunakan untuk seluruh anggota keluarga.
    Isi 360 helai membuatnya lebih awet dan ekonomis, cocok untuk digunakan di rumah, kantor, mobil, atau dibawa bepergian. 
    Tisu ini tidak mudah sobek saat digunakan, namun tetap menjaga kelembutan sehingga nyaman dan aman untuk kulit sensitif sekalipun.
    ', true, 3, 20000, 43),
('Prima', 40000, 'images/prima-600ml.jpg', 'MINUMAN', '
    "Segar, Terjangkau, dan Aman Dikonsumsi Setiap Hari"
    Air Mineral Prima 600 ml merupakan pilihan air minum praktis untuk menemani aktivitas harian Anda.
    Diproses melalui sistem penyaringan modern hingga menghasilkan air yang jernih.
    Jaminan Keaslian & Kualitas Produk:
    ✔ Segel botol resmi dan utuh
    ✔ Tanggal kedaluwarsa jelas & terbaru
    ✔ Dikemas langsung oleh pabrik dengan standar food grade & higienis
    ✔ 1 Karton isi 24 Botol
    ', true, null, null, 44),
('VIT Gelas', 26000, 'images/vit-gelas.jpg', 'MINUMAN', '
    "Praktis, Higienis, dan Siap Saji"
    VIT Gelas 200 ml adalah air mineral murni yang diproses dengan standar kualitas tinggi untuk memastikan rasa yang segar serta aman dikonsumsi.
    Dikemas menggunakan plastik food grade dan penutup pelindung segel, VIT gelas menawarkan kenyamanan minum tanpa repot membuka botol—tinggal buka segel dan minum.
    Jaminan Keaslian & Kualitas Produk:
    ✔ Segel cup utuh & resmi pabrik
    ✔ Tanggal kedaluwarsa jelas & terbaru
    ✔ Diproduksi dengan standar higienis dan food grade
    ✔ 1 Karton isi 48 Cup/Gelas
    ', true, null, null, 45),
('Air Isi Ulang', 8000, 'images/isiulang.jpg', 'REFIL', '
    "Harga Terjangkau, Kualitas Tetap Terjamin"
    Air isi ulang kami diproses menggunakan sistem filtrasi modern yang terdiri dari penyaringan berlapis, reverse osmosis (RO).
    Proses ini memastikan air yang dihasilkan jernih, bebas bau, bebas bakteri, dan aman untuk dikonsumsi setiap hari.
    Dengan harga ekonomis namun tetap mengutamakan kualitas dan standar kebersihan.
    Jaminan Kebersihan & Kualitas:
    ✔ Galon dicuci & disterilkan sebelum diisi
    ✔ Higienis, aman, dan terjaga dari kontaminasi
    ✔ Diambil langsung saat pesanan, bukan stok lama
    ', true, null, null, 46)
) as seed(name, price, image_url, category, description, tambahan_biaya, promo_qty, promo_price, sort_order)
where not exists (select 1 from public.catalog_products existing where existing.name = seed.name);
